# Site settings
title: Stacks | Stack Overflow
description: The UI pattern library for the Stack Overflow, Stack Overflow Carers, and the Stack Exchange Network.
baseurl: /pages/Design/stacks # the subpath of your site, e.g. /blog
url: https://gh.stackoverflow.com/pages/Design/stacks/ # the base hostname & protocol for your site

# Build settings
markdown: kramdown

lib: assets
img: assets/images
css: assets/stylesheets
js: assets/javascripts
stickers: assets/stickers

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, docs-*.html, .asset-cache]

collections:
    components:
        output: true
        permalink: /:collection/:path/
    resources:
        output: true
        permalink: /:collection/:path/

defaults:
    - scope:
        path: ""
        type: components
      values:
        layout: default
    - scope:
        path: ""
        type: resources
      values:
        layout: default
