[Settings]
  ID = "34ae802e-fb42-4bab-8814-9fac9e119037"

[Build]
  base = "docs/"
  build = "jekyll build"
  publish = "docs/_site/"

redirects = [
  {from = "/guidelines/using-stacks", to = "/product/guidelines/using-stacks"},
  {from = "/guidelines/customization", to = "/product/guidelines/customization"},
  {from = "/guidelines/responsiveness", to = "/product/guidelines/responsiveness"},
  {from = "/resources/icons", to = "/product/resources/icons"},
  {from = "/base/borders", to = "/product/base/borders"},
  {from = "/base/box-shadow", to = "/product/base/box-shadow"},
  {from = "/base/box-sizing", to = "/product/base/box-sizing"},
  {from = "/base/colors", to = "/product/base/colors"},
  {from = "/base/cursors", to = "/product/base/cursors"},
  {from = "/base/display", to = "/product/base/display"},
  {from = "/base/floats", to = "/product/base/floats"},
  {from = "/base/grid", to = "/product/base/grid"},
  {from = "/base/opacity", to = "/product/base/opacity"},
  {from = "/base/overflow", to = "/product/base/overflow"},
  {from = "/base/pointer-events", to = "/product/base/pointer-events"},
  {from = "/base/position", to = "/product/base/position"},
  {from = "/base/spacing", to = "/product/base/spacing"},
  {from = "/base/typography", to = "/product/base/typography"},
  {from = "/base/vertical-alignment", to = "/product/base/vertical-alignment"},
  {from = "/base/width-height", to = "/product/base/width-height"},
  {from = "/base/z-index", to = "/product/base/z-index"},
  {from = "/components/avatars", to = "/product/components/avatars"},
  {from = "/components/badges", to = "/product/components/badges"},
  {from = "/components/banners", to = "/product/components/banners"},
  {from = "/components/buttons", to = "/product/components/buttons"},
  {from = "/components/button-groups", to = "/product/components/button-groups"},
  {from = "/components/cards", to = "/product/components/cards"},
  {from = "/components/checkbox", to = "/product/components/checkbox"},
  {from = "/components/inputs", to = "/product/components/inputs"},
  {from = "/components/labels", to = "/product/components/labels"},
  {from = "/components/links", to = "/product/components/links"},
  {from = "/components/modals", to = "/product/components/modals"},
  {from = "/components/notices", to = "/product/components/notices"},
  {from = "/components/progress-bars", to = "/product/components/progress-bars"},
  {from = "components/radio", to = "/product/components/radio"},
  {from = "/components/select", to = "/product/components/select"},
  {from = "components/sidebar-widgets", to = "/product/components/sidebar-widgets"},
  {from = "/components/tables", to = "/product/components/tables"},
  {from = "/components/tabs", to = "/product/components/tabs"},
  {from = "/components/tags", to = "/product/components/tags"},
  {from = "/components/textarea", to = "/product/components/textarea"}]