[Settings]
  ID = "34ae802e-fb42-4bab-8814-9fac9e119037"

[Build]
  Publish = ""
  Functions = ""
  base = "docs"

[context.netlify-configuration.build]
  base = "docs"
  build = "jekyll build"
  public = "docs/_site"
